- 각 변수는 어떤 값을 갖는가?
- 각 품종의 데이터 수는 동일한가?
- 꽃잎과 꽃받침의 크기는 어떻게 분포하는가?
- 이상치로 보이는 관측값은 존재하는가?
- 꽃잎 길이와 너비는 서로 어떠한 관계를 갖는가?
- 품종에 따라 측정값의 분포가 다른가?
- 여러 수치형 변수 중 어떤 변수들이 강한 관계를 갖는가?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

In [2]:
sns.set_theme(
    context='notebook',
    style='whitegrid',
)

In [6]:
iris = load_iris(as_frame=True)

df = iris.frame.copy()

In [7]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [10]:
df = df.rename(
    columns={
        'sepal length (cm)': 'sepal_length',
        'sepal width (cm)': 'sepal_width',
        'petal length (cm)': 'petal_length',
        'petal width (cm)': 'petal_width',
    }
)

df.head()

   sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
target_map = dict(enumerate(iris.target_names))

df['species'] = df['target'].map(target_map)
df = df.drop(columns='target')

In [17]:
df.shape

(150, 5)

In [18]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [19]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [20]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [22]:
numeric_columns = df.select_dtypes(include='number').columns.to_list()

print(type(numeric_columns))
print(numeric_columns)

<class 'list'>
['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [23]:
categorical_columns = df.select_dtypes(exclude='number').columns.to_list()

print(type(categorical_columns))
print(categorical_columns)

<class 'list'>
['species']

In [24]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64